Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/', include('home.urls'), name='home'),
    path('', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/follows/', views.follows, name='follows'),
    path('<str:username>/follows/<str:category>/<int:number>', views.followsInDetail, name='followsInDetail'),
    
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('<str:username>/', views.main, name='main'),
    path('<str:username>/<str:category>/<int:number>/', views.detail, name='detail'),
    path('<str:username>/create/', views.create, name='create'),
    path('<str:username>/edit_introduce/', views.edit_introduce, name='edit_introduce'),
    path('<str:username>/<str:category>/<int:number>/delete/', views.delete, name='delete'),
    path('<str:username>/<str:category>/<int:number>/update/', views.update, name='update'),

    path('<str:username>/<str:category>/<int:number>/likes-async/', views.likes_async, name='likes-async'),

    path('<str:username>/<str:category>/<int:number>/comments/create/', views.comment_create, name='comment_create'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/likes-async/', views.comment_likes_async, name='comment-likes-async'),  
  
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/create/', views.reply_create, name='reply_create'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/<int:reply_id>/delete/', views.reply_delete, name='reply_delete'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/<int:reply_id>/update/', views.reply_update, name='reply_update'),

    path('<str:username>/category', views.category, name='category'),
    path('<str:username>/category/create', views.Create_category, name='createCategory'),
    path('<str:username>/category/delete', views.Delete_category, name='deleteCategory'),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from accounts.models import *
from main.models import *
from main.forms import *
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.

# 홈
def home(request):
    # 전체 이용자 포스트 확인을 위한 전달 변수
    page = request.GET.get('page_posts','1')
    posts = Post.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 5)
    page_obj = paginator.get_page(page)
    page_obj_nb = None

    # 로그인한 사용자인 경우
    if request.user.is_authenticated:
        # 이웃 포스트 확인을 위한 전달 변수
        page_nb = request.GET.get('page_nb','1')
        posts_nb = Post.objects.filter(user__in=request.user.followings.all()).order_by('-created_at')
        paginator_nb = Paginator(posts_nb, 3)
        page_obj_nb = paginator_nb.get_page(page_nb)

    context = {
        'posts':page_obj,
        'posts_nb':page_obj_nb,
    }

    return render(request, 'home.html', context)

home/templates/userPostList/_allREstaurants.html
<div id='allRestaurants' class="m-2 rounded-2 d-flex" style="flex-direction: column;">
    {% for post in posts %}
        {% if post.tag == 'RESTAURANT' %}

            <!-- 포스트에 관한 정보 -->
            <div class="d-flex align-items-center" style="width: 100%;">
                <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="{{ post.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>

                <div>
                    <p class="m-0" style="font-size: 0.75rem;"><a href="{% url 'main:main' username=post.user.username %}" class="link-dark  link-underline-opacity-0">{{post.user}}</a></p>
                    <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ post.updated_at }}</p>
                </div>

                <!-- 이웃 기능 -->
                {% if user != post.user and user.is_authenticated %}
                    {% if user in post.user.followers.all %}
                        <a href="{% url 'accounts:follows' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                    {% else %}
                        <a href="{% url 'accounts:follows' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                    {% endif %}
                {% endif %}
            </div>

            <!-- 포스트 링크 -->
            <a href="{% url 'main:detail' username=post.user.username category=post.category.name number=post.id %}" class="link-dark link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
            <h5 class="fw-bold mt-1">{{ post.title }}</h5>
            <p style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 3;">
                {{ post.content}}
            </p>
            </a>
            <hr class="mt-0">
        {% endif %}
    {% endfor %}
</div>

home/templates/userPostList/_allhobbies.html
<div id='allHobbies' class="m-2 rounded-2 d-flex" style="flex-direction: column;">
    {% for post in posts %}
        {% if post.tag == 'HOBBY' %}

            <!-- 포스트에 관한 정보 -->
            <div class="d-flex align-items-center" style="width: 100%;">
                <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="{{ post.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>

                <div>
                    <p class="m-0" style="font-size: 0.75rem;"><a href="{% url 'main:main' username=post.user.username %}" class="link-dark  link-underline-opacity-0">{{post.user}}</a></p>
                    <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ post.updated_at }}</p>
                </div>

                <!-- 이웃 기능 -->
                {% if user != post.user and user.is_authenticated %}
                    {% if user in post.user.followers.all %}
                        <a href="{% url 'accounts:follows' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                    {% else %}
                        <a href="{% url 'accounts:follows' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                    {% endif %}
                {% endif %}
            </div>

            <!-- 포스트 링크 -->
            <a href="{% url 'main:detail' username=post.user.username category=post.category.name number=post.id %}" class="link-dark link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                <h5 class="fw-bold mt-1">{{ post.title }}</h5>
                <p style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 3;">
                    {{ post.content}}
                </p>
            </a>
            <hr class="mt-0">
        {% endif %}
    {% endfor %}
</div>

home/templates/userPostList/_pagination.html
<nav class="mt-auto">
    <ul class="pagination justify-content-center">

      <!-- 포스트가 없는 경우 -->
      {% if posts_nb == None %}

        <!-- 이전 페이지 -->
        {% if posts.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page_posts={{ posts.previous_page_number }}">이전</a>
          </li>
        {% else %}
          <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
          </li>
        {% endif %}

        <!-- 현재 페이지 -->
        {% for page_number in posts.paginator.page_range %}
          {% if page_number == posts.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page_posts={{ page_number }}">{{ page_number }}</a>
            </li>
          {% else %}
            <li class="page-item">
                <a class="page-link" href="?page_posts={{ page_number }}">{{ page_number }}</a>
            </li>
          {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if posts.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page_posts={{ posts.next_page_number }}">다음</a>
          </li>
        {% else %}
          <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
          </li>
        {% endif %}
      
      <!-- 포스트가 있는 경우 -->
      {% else %}
          
        <!-- 이전 페이지 -->
        {% if posts.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page_posts={{ posts.previous_page_number }}&page_nb={{ page_nb }}">이전</a>
          </li>
        {% else %}
          <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
          </li>
        {% endif %}

        <!-- 현재 페이지 -->
        {% for page_number in posts.paginator.page_range %}
          {% if page_number == posts.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page_posts={{ page_number }}&page_nb={{ page_nb }}">{{ page_number }}</a>
            </li>
          {% else %}
            <li class="page-item">
                <a class="page-link" href="?page_posts={{ page_number }}&page_nb={{ page_nb }}">{{ page_number }}</a>
            </li>
          {% endif %}
        {% endfor %}

        <!-- 다음페이지 -->
        {% if posts.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page_posts={{ posts.next_page_number }}&page_nb={{ page_nb }}">다음</a>
          </li>
        {% else %}
          <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
          </li>
        {% endif %}
        
      {% endif %}
    </ul>
</nav>

home/templates/userPostList/_tag.html
<div>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#" onclick="showContent('allPosts')">전체</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#" onclick="showContent('allRestaurants')">맛집</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#" onclick="showContent('allHobbies')">취미</a>
        </li>
    </ul>
</div>

<!-- 맛집 -->
<div id="allRestaurantsContent" class="content" style="display: none;">
    {% include './_allRestaurants.html' %}

</div>

<!-- 취미 -->
<div id="allhobbiesContent" class="content" style="display: none;">
    {% include './_allhobbies.html' %}
</div>

home/templates/userPostList/userPostList.html
<article class="m-2 p-1 rounded-2 d-flex" style="border: 2px solid black; flex-direction: column;">
    <!-- tag -->
    {% include './_tag.html' %}

    <!-- 전체 포스트 -->
    <div id="allPostsContent" class="content">
        <div id="allPosts" class="m-2 rounded-2 d-flex" style="flex-direction: column;">
            {% for post in posts %}
            
                <!-- 포스트에 관한 정보 -->
                <div class="d-flex align-items-center" style="width: 100%;">
                    <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                        <img src="{{ post.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                    </div>
        
                    <div>
                        <p class="m-0" style="font-size: 0.75rem;"><a href="{% url 'main:main' username=post.user.username %}" class="link-dark  link-underline-opacity-0">{{post.user}}</a></p>
                        <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ post.updated_at }}</p>
                    </div>

                    <!-- 이웃 기능 -->
                    {% if user != post.user and user.is_authenticated %}
                        {% if user in post.user.followers.all %}
                            <a href="{% url 'accounts:follows' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                        {% else %}
                            <a href="{% url 'accounts:follows' username=post.user %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                        {% endif %}
                    {% endif %}
                </div>
                
                <!-- 포스트 링크 -->
                <a href="{% url 'main:detail' username=post.user.username category=post.category.name number=post.id %}" class="link-dark link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                <h5 class="fw-bold mt-1">{{ post.title }}</h5>
                <p style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 3;">
                    {{ post.content}}
                </p>
                </a>
                <hr class="mt-0">
            {% endfor %}
        </div>
    </div>

    <!-- 페이지네이션 -->
    {% include './_pagination.html' %}
    <script type="text/javascript" src="/static/js/userPostList.js"></script>
</article>