Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/', include('home.urls'), name='home'),
    path('', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/follows/', views.follows, name='follows'),
    path('<str:username>/follows/<str:category>/<int:number>', views.followsInDetail, name='followsInDetail'),
    
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('<str:username>/', views.main, name='main'),
    path('<str:username>/<str:category>/<int:number>/', views.detail, name='detail'),
    path('<str:username>/create/', views.create, name='create'),
    path('<str:username>/edit_introduce/', views.edit_introduce, name='edit_introduce'),
    path('<str:username>/<str:category>/<int:number>/delete/', views.delete, name='delete'),
    path('<str:username>/<str:category>/<int:number>/update/', views.update, name='update'),

    path('<str:username>/<str:category>/<int:number>/likes-async/', views.likes_async, name='likes-async'),

    path('<str:username>/<str:category>/<int:number>/comments/create/', views.comment_create, name='comment_create'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/likes-async/', views.comment_likes_async, name='comment-likes-async'),  
  
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/create/', views.reply_create, name='reply_create'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/<int:reply_id>/delete/', views.reply_delete, name='reply_delete'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/<int:reply_id>/update/', views.reply_update, name='reply_update'),

    path('<str:username>/category', views.category, name='category'),
    path('<str:username>/category/create', views.Create_category, name='createCategory'),
    path('<str:username>/category/delete', views.Delete_category, name='deleteCategory'),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from accounts.models import *
from main.models import *
from main.forms import *
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# Create your views here.

# 홈
def home(request):
    # 전체 이용자 포스트 확인을 위한 전달 변수
    page = request.GET.get('page_posts','1')
    posts = Post.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 5)
    page_obj = paginator.get_page(page)
    page_obj_nb = None

    # 로그인한 사용자인 경우
    if request.user.is_authenticated:
        # 이웃 포스트 확인을 위한 전달 변수
        page_nb = request.GET.get('page_nb','1')
        posts_nb = Post.objects.filter(user__in=request.user.followings.all()).order_by('-created_at')
        paginator_nb = Paginator(posts_nb, 3)
        page_obj_nb = paginator_nb.get_page(page_nb)

    context = {
        'posts':page_obj,
        'posts_nb':page_obj_nb,
    }

    return render(request, 'home.html', context)

home/templates/aside/profile.html
<!-- 로그인 사용자 정보를 보여주는 기능 -->
<div class="m-2 rounded-2 d-flex" style="border: 2px solid rgb(0, 0, 0); flex-direction: column;">

    <!-- 사용자 정보 -->
    <div class="d-flex align-items-center" style="width: 100%;">
        <div class="m-1" style="width: 50px; height: 50px; border-radius: 70%; overflow: hidden;">
            <img src="{{ user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
        </div>

        <div>
            <p style="font-size: 0.75rem;">{{ user.username }}</p>
        </div>
        <button onclick="location.href='{% url 'accounts:logout' %}'" type="button" class="btn btn-secondary ms-auto me-1" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">로그아웃</button>
    </div>

    <!-- 이동 기능 -->
    <div class="btn-group mt-2" role="group" aria-label="Basic example">
        <button onclick="location.href='{% url 'main:main' username=request.user.username %}'" type="button" class="btn btn-primary">내블로그</button>
        <button onclick="location.href='{% url 'main:create' username=request.user.username %}'" type="button" class="btn btn-primary">글쓰기</button>
    </div>
</div>

home/templates/aside/sign.html
<!-- accounts의 기능으로 이동하는 버튼 -->
<div class="m-2 p-1 rounded-2 d-flex" style="border: 2px solid rgb(0, 0, 0); flex-direction: column;">
    <button onclick="location.href='{% url 'accounts:login' %}'" type="button" class="btn btn-primary my-1">
        로그인
    </button>
    <button onclick="location.href='{% url 'accounts:signup' %}'" type="button" class="btn btn-primary my-1">
        회원가입
    </button>
</div>