Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/', include('home.urls'), name='home'),
    path('', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/follows/', views.follows, name='follows'),
    path('<str:username>/follows/<str:category>/<int:number>', views.followsInDetail, name='followsInDetail'),
    
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('<str:username>/', views.main, name='main'),
    path('<str:username>/<str:category>/<int:number>/', views.detail, name='detail'),
    path('<str:username>/create/', views.create, name='create'),
    path('<str:username>/edit_introduce/', views.edit_introduce, name='edit_introduce'),
    path('<str:username>/<str:category>/<int:number>/delete/', views.delete, name='delete'),
    path('<str:username>/<str:category>/<int:number>/update/', views.update, name='update'),

    path('<str:username>/<str:category>/<int:number>/likes-async/', views.likes_async, name='likes-async'),

    path('<str:username>/<str:category>/<int:number>/comments/create/', views.comment_create, name='comment_create'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/likes-async/', views.comment_likes_async, name='comment-likes-async'),  
  
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/create/', views.reply_create, name='reply_create'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/<int:reply_id>/delete/', views.reply_delete, name='reply_delete'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/<int:reply_id>/update/', views.reply_update, name='reply_update'),

    path('<str:username>/category', views.category, name='category'),
    path('<str:username>/category/create', views.Create_category, name='createCategory'),
    path('<str:username>/category/delete', views.Delete_category, name='deleteCategory'),

]

main/models.py
from django.db import models
from django.urls import reverse
from django_resized import ResizedImageField
from django.conf import settings
from accounts import models as accounts_model

# Create your models here.

# 카테고리 모델링
class Category(models.Model):
    owner = models.ForeignKey(accounts_model.User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('main:main')

# 포스트 모델링
class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default='1')
    TAG_CHOICES = [
        ('RESTAURANT', '맛집'),
        ('HOBBY', '취미'),
    ]
    title = models.CharField(max_length=100)
    content = models.TextField()
    image = ResizedImageField(
        size = [500, 500],
        crop = ['middle', 'center'],
        upload_to = 'image/%Y/%m',
        blank=True,
        null=True
    )
    tag = models.CharField(max_length=30, choices = TAG_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')

    def __str__(self):
        return self.title
    
# 댓글 모델링
class Comment(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content[:20]

# 답글 모델링
class Reply(models.Model):
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content[:20]

main/forms.py
from django import forms
from .models import *
from accounts.models import *

# 포스트 작성 폼
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'image', 'tag', 'category',)

class EditIntroduceForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('introduce',)
    introduce = forms.CharField(widget=forms.Textarea(attrs={'rows': 5}))

# 댓글 작성 폼
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('post', 'user', 'like_users', )
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': '3',
                    'placeholder': '댓글을 입력해주세요',
                }
            ),
        }
        labels = {
            'content': '',
        }

# 답글 작성 폼
class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        exclude = ('user', 'post', 'comment',)
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control mt-2',
                    'rows': '3',
                    'placeholder': '답글을 입력해주세요',
                }
            ),
        }
        labels = {
            'content': '',
        }

main/views.py
from django.shortcuts import render, redirect
from accounts.models import *
from .models import *
from accounts.forms import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.core.paginator import Paginator

# Create your views here.

# 홈으로 보내는 기능
def home(request):
    return redirect('home:home')


# 블로그 메인 기능
def main(request, username):
    # 블로그 주인
    try:
        owner = User.objects.get(username=username)
    except User.DoesNotExist:
        return HttpResponse("잘못된 접근입니다.") 
    
    # 포스트 리스트
    postlist = Post.objects.filter(user_id=owner.id)
    sorted_posts = postlist.all().order_by('-created_at')
    post = sorted_posts.first()
    
    # 페이지네이션
    page = request.GET.get('page_posts','1')
    paginator = Paginator(sorted_posts, 4)
    page_obj = paginator.get_page(page)

    # 카테고리
    categories = Category.objects.filter(owner_id=owner.id)
    categoryList = {}
    for category in categories:
        if category not in categoryList.keys():
            if Post.objects.filter(category__name=category, user_id=owner.id).order_by('-id').first() == None:
                categoryList[category] = 1
            else:
                categoryList[category] = Post.objects.filter(category__name=category, user_id=owner.id).order_by('-id').first().id

    category_items = list(categoryList.items())

    # 댓글, 답글 폼
    comment_form = CommentForm()
    reply_form = ReplyForm()
    context = {
        'owner':owner,
        'username':username,
        'postlist':postlist,
        'category':category,
        'sorted_posts':page_obj,
        'categoryList':categoryList,
        'category_items': category_items,
        'post':post,
        'comment_form':comment_form,
        'reply_form':reply_form,
    }

    return render(request, 'main.html', context)


# 포스트 작성 기능
@login_required
def create(request, username):
    # 블로그 주인
    owner = User.objects.get(username=username)

    # 카테고리
    categories = Category.objects.filter(owner_id=owner.id)
    if not categories:
        Category.objects.create(name='기본 카테고리' ,owner=owner)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.category_id = request.POST.get('category')
            post.save()
            return redirect('main:detail', username=username, category=post.category.name ,number=post.id)
    else:
        form = PostForm()
    
    context = {
        'form': form,
        'categories': categories,
        'owner':owner,
    }

    return render(request, 'writepage.html', context)


# 포스트 상세 페이지
def detail(request, username, category, number):
    # 블로그 주인
    owner = User.objects.get(username=username)

    # 포스트
    postlist = Post.objects.filter(category__name=category, user_id=owner.id)
    sorted_posts = postlist.all().order_by('-created_at')
    if not postlist.filter(id=number).exists():
        return redirect('main:main', username=username)
    else:
        post = postlist.get(id=number)

    # 페이지네이션
    page = request.GET.get('page_posts','1')
    paginator = Paginator(sorted_posts, 4)
    page_obj = paginator.get_page(page)

    # 카테고리
    categories = Category.objects.filter(owner_id=owner.id)
    categoryList = {}
    for category in categories:
        if category not in categoryList.keys():
            if Post.objects.filter(category__name=category, user_id=owner.id).order_by('-id').first() == None:
                categoryList[category] = 1
            else:
                categoryList[category] = Post.objects.filter(category__name=category, user_id=owner.id).order_by('-id').first().id
    category_items = list(categoryList.items())

    # 댓글, 답글 폼
    comment_form = CommentForm()
    reply_form = ReplyForm()

    context = {
        'owner':owner,
        'username':username,
        'category':category,
        'postlist':postlist,
        'sorted_posts':page_obj,
        'post':post,
        'categoryList':categoryList,
        'category_items': category_items,
        'comment_form':comment_form,
        'reply_form':reply_form,
    }

    return render(request, 'detail.html', context)


# 자기 소개 수정 기능
@login_required
def edit_introduce(request, username):
    # 블로그 주인
    owner = User.objects.get(username=username)

    # 요청자가 블로그 주인인지 확인
    if request.user != owner:
        return JsonResponse(status=403)
    
    # 자기 소개 수정
    if request.method == 'POST':
        introduce = request.POST.get('introduce')
        owner.blog.introduce = introduce
        owner.blog.save()

        data = {
            'introduce': owner.blog.introduce,
        }

        return JsonResponse(data)

    return JsonResponse(status=405)

# 포스트 삭제
@login_required
def delete(request, username, category, number):
    post = Post.objects.get(id=number)
    # 사용자 확인
    if request.user == post.user:
        post.delete()

    return redirect('main:main', username=username)


# 포스트 업데이트
@login_required
def update(request, username, category, number):
    # 작성을 위한 정보
    owner = User.objects.get(username=username)
    categories = Category.objects.filter(owner_id=owner.id)
    post = Post.objects.get(id=number)

    # 사용자 확인
    if request.user != post.user:
        return redirect('main:detail', username=username, category=post.category.name, number=number)

    # 수정 데이터 저장
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('main:detail', username=username, category=post.category.name, number=number)
    
    # 요청이 POST가 아닌 경우
    else:
        form = PostForm(instance=post)

    context = {
        'form': form,
        'post': post,
        'categories': categories,
    }

    return render(request, 'writepage.html', context)


# 카테고리 관리 기능
@login_required
def category(request, username):
    # 블로그 주인
    owner = User.objects.get(username=username)

    # 요청자가 주인일 경우
    if request.user == owner:
        categories = Category.objects.filter(owner_id=owner.id).order_by('name')
        standard = categories.first()

        # 카테고리가 없는 경우
        if not categories:
            Category.objects.create(name='기본 카테고리' ,owner=owner)

        context = {
            'owner':owner,
            'categories':categories,
            'standard':standard,
        }

        return render(request, 'category/category.html', context)
    
    else:
        return redirect('main:main', username=username)


# 카테고리 생성 기능
@login_required
def Create_category(request, username):
    owner = User.objects.get(username=username)
    category_name = request.POST['categoryName']
    new_categories = Category(name=category_name, owner_id=owner.id)
    new_categories.save()
    categories = Category.objects.filter(owner_id=owner.id).order_by('name')
    context = {
        'owner':owner,
        'categories':categories,
        }
    return render(request, 'category/setting.html', context)


# 카테고리 삭제 기능
@login_required
def Delete_category(request, username):
    category_id = request.POST['categoryId']    
    delete_category = Category.objects.get(id = category_id)
    delete_category.delete()
    return redirect('main:category', username=username)


# 포스트 공감 기능
@login_required
def likes_async(request, username, category, number):
    user = request.user
    post = Post.objects.get(id=number)

    # 요청자가 이미 공감하는 경우
    if user in post.like_users.all():
        post.like_users.remove(user)
        status = False

    # 요청자가 공감하지 않는 경우
    else:
        post.like_users.add(user)
        status = True

    context = {
        'status': status,
        'count': len(post.like_users.all()),
        'username': username,
        'category': category,
        'number': number,
    }

    return JsonResponse(context)


# 댓글 작성 기능
@login_required
def comment_create(request, username, category, number):
    # 블로그 주인
    owner = User.objects.get(username=username)

    # 댓글 작성 폼
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post_id = number
        comment.save()

    data = {
        'owner': owner.username,
        'username': username,
        'category': category,
        'number': number,
        'comment_user_id': comment.user.id,
        'comment_user_profile_image_url': comment.user.profile_image.url,
        'comment_username': comment.user.username,
        'comment_updated_at': comment.updated_at,
        'comment_created_at': comment.created_at,
        'comment_id': comment.id,
        'comment_content': comment.content,
        'like_users': comment.like_users.count()
    }

    return JsonResponse(data)


# 댓글 수정 기능
@login_required
def comment_update(request, username, category, number, comment_id):
    # 수정하려는 댓글
    comment = Comment.objects.get(id=comment_id)

    # 요청자가 댓글 작성자인지 확인
    if request.user != comment.user:
        return JsonResponse(status=403)
    
    # 댓글 수정
    if request.method == 'POST':
        content = request.POST.get('content') 
        comment.content = content
        comment.save()

        data = {
            'content': comment.content,
            'updated_at': comment.updated_at.strftime('%Y-%m-%d %H:%M:%S')

        }

        return JsonResponse(data)
    
    return JsonResponse(status=405)


# 댓글 삭제 기능
@login_required
def comment_delete(request, username, category, number, comment_id):
    # 삭제하려는 댓글
    comment = Comment.objects.get(id=comment_id)

    # 요청자가 댓글 작성자인지 확인
    if request.user != comment.user:

main/templates/nowPost/comment&reply.html
<!-- 포스트에 달린 댓글 반복문 -->
{% for comment in post.comment_set.all %}

    <!-- comment -->
    <div class="d-flex align-items-center" style="width: 100%;">
        <!-- 댓글 작성자 정보 -->
        <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
            <img src="{{ comment.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
        </div>
        <div class="mx-2">
            <p class="m-0" style="font-size: 1rem;">{{ comment.user }}</p>
            <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ comment.updated_at|date:"Y년 n월 j일 A g:i" }}</p>
        </div>
        <div class="ms-auto my-0 py-0">
            <!-- 댓글 수정 및 삭제 -->
            <div class="ms-auto">
                {% if user == comment.user %}
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                        <ul class="dropdown-menu">
                            <li><button class="dropdown-item" onclick="showUpdateForm('{{ comment.id }}', '{{ comment.content }}')">수정하기</button></li>
                            <li><button onclick="commentDelete('{{owner.username}}','{{post.category.name}}','{{post.id}}','{{comment.id}}');" class="dropdown-item" href="#">삭제하기</button></li>
                        </ul>
                    </div>
                {% else %}
                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" style="visibility: hidden;"></button>
                    </div>
                {% endif %}
            </div>
            <!-- 댓글 공감 버튼 -->
            <div class="my-0 py-0 me-2">
                {% if user in comment.like_users.all %}
                    <i class="bi bi-heart-fill comment_heart align-self-center " style="color:red; font-size: 1rem;" data-post-id="{{ post.id }}" data-comment-id="{{ comment.id }}" data-username="{{ username }}" data-category="{{ category }}">{{ comment.like_users.all|length }}</i> 
                {% else %}
                    <i class="bi bi-heart comment_heart align-self-center" style="font-size: 1rem;" data-post-id="{{ post.id }}" data-comment-id="{{ comment.id }}" data-username="{{ username }}" data-category="{{ category }}">{{ comment.like_users.all|length }}</i>                
                {% endif %}
                </button>
            </div>
        </div>
    </div>
    
    <!-- 댓글 내용 -->
    <p class="ms-1">{{ comment.content }}</p>

    <!-- 댓글 수정 폼 -->
    <div id="comment-{{ comment.id }}-update-form" style="display: none;">
        <form onsubmit="updateComment('{{owner.username}}', '{{post.category.name}}', '{{post.id}}', '{{comment.id}}', this.content.value); return false;">
            <textarea name="content" id="comment-{{ comment.id }}-update-content" rows="3" class="form-control">{{ comment.content }}</textarea>
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary mt-2 mb-2 float-right">수정하기</button>
            </div>
        </form>
    </div>

    <!-- reply -->
    <div class="ms-2">
        <!-- 댓글에 달린 답글 반복문 -->
        {% for reply in comment.reply_set.all %}

            <!-- 답글 작성자 정보 -->
            <div class="d-flex align-items-center" style="width: 100%;">
                <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="{{ reply.user.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
                <div>
                    <p class="m-0" style="font-size: 1rem;">{{ reply.user }}</p>
                    <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ reply.updated_at|date:"Y년 n월 j일 A g:i" }}</p>
                </div>
            
                <!-- 답글 수정 및 삭제 -->
                {% if user == reply.user %}
                <div class="dropdown ms-auto">
                    <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                    <ul class="dropdown-menu">
                        <li>
                            <button type="button" class="dropdown-item" onclick="showUpdateReplyForm('{{ reply.id }}', '{{ reply.content }}')">수정하기</button>
                        </li>
                        <li>
                            <button onclick="replyDelete('{{owner.username}}','{{post.category.name}}','{{post.id}}','{{comment.id}}','{{reply.id}}');" class="dropdown-item" href="#">삭제하기</button>
                        </li>
                    </ul>
                </div>
                {% endif %}
            
            </div>

            <!-- 답글 내용 -->
            <p class="ms-3">{{ reply.content }}</p>
            
            <!-- 답글 수정 폼 -->
            <div id="reply-{{ reply.id }}-update-form" style="display: none;">
                <form onsubmit="updateReply('{{owner.username}}', '{{post.category.name}}', '{{post.id}}', '{{comment.id}}', '{{ reply.id }}', this.content.value); return false;">
                    <textarea name="content" id="reply-{{ reply.id }}-update-content" rows="3" class="form-control">{{ reply.content }}</textarea>
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary mt-2 mb-2 float-right">수정하기</button>
                    </div>
                </form>
            </div>
        {% endfor %}        
    </div>

    <!-- 답글 버튼 -->
    <div class="d-flex align-items-center" style="width: 100%;">
        <button type="button" class="btn btn-outline-secondary" data-bs-toggle="collapse" data-bs-target="#reply-list-{{ post.id }}-{{ comment.id }}" aria-expanded="false" aria-controls="reply" style="--bs-btn-padding-y: 0rem; --bs-btn-padding-x: .3rem; --bs-btn-font-size: .75rem;">답글</button>
    </div>

    <!-- 답글 작성 폼 -->
    <div class="collapse reply_form" id="reply-list-{{ post.id }}-{{ comment.id }}">
        {% if user.is_authenticated %}
        <form action="{% url 'main:reply_create' username=owner.username category=post.category.name number=post.id comment_id=comment.id %}" method="POST" class="reply-Form">
            {% csrf_token %}
            {{ reply_form }}
            <div class="mt-3 d-flex">
                <input type="submit" class="ms-auto btn btn-secondary" value="답글 작성">
            </div>
        </form>
        {% endif %}
    </div>

    <hr>
{% endfor %}

<!-- 댓글 작성 폼 -->
<div class="comment_form">
    {% if user.is_authenticated %}
    <form action="{% url 'main:comment_create' username=owner.username category=post.category.name number=post.id %}" method="POST" class="comment-Form">
        {% csrf_token %}
        {{ comment_form }}
        <div class="mt-3 d-flex">
            <input type="submit" class="ms-auto btn btn-secondary" value="댓글 작성">
        </div>
    </form>
    {% endif %}
</div>

main/templates/nowPost/likes.html
<p class="d-inline-flex gap-1">
    <!-- 포스트에 공감하는 사람들을 표시하는 버튼 -->
    <div class="btn-group" role="group" aria-label="">
        <!-- 공감 콜랩스 -->
        <button class="btn btn-outline-primary" data-bs-toggle="collapse" href="#likeUsers" role="button" aria-expanded="false">
            공감
        </button>
        <!-- 공감 관련 정보 -->
        <button type="button" class="btn btn-outline-primary" id="like-button-{{ post.id }}" data-username="{{ username }}" data-category="{{ category }}">
            {% if user in post.like_users.all %}
                <i class="bi bi-heart-fill heart align-self-center" style="color:red; font-size: 1rem;" data-post-id="{{ post.id }}">{{ post.like_users.all|length }} </i>
            {% else %}
                <i class="bi bi-heart heart align-self-center" style="font-size: 1rem;" data-post-id="{{ post.id }}">{{ post.like_users.all|length }} </i>
            {% endif %}
        </button>
    </div>

    <!-- 댓글 콜랩스 -->
    <button class="btn btn-outline-primary show" type="button" data-bs-toggle="collapse" data-bs-target="#comment" aria-expanded="false" aria-controls="comment">
      댓글
    </button>
</p>

<!-- 포스트에 공감하는 사람들에 대한 정보 -->
<div class="collapse" id="likeUsers">
    <div class="overflow-auto">
        {% for likeuser in post.like_users.all %}
            <div class="d-flex m-1 float-start" style="height: 30px; width: 200px;">
                <div style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                    <img src="{{ likeuser.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                </div>
                <div class="mx-1">
                    <p style="font-size: 0.75rem;">{{ likeuser.username }}</p>
                </div>

                <!-- 이웃 추가, 해제 기능 -->
                {% if user != likeuser and user.is_authenticated %}
                    {% if user in likeuser.followers.all %}
                        <a href="{% url 'accounts:followsInDetail' username=likeuser.username category=post.category.name number=post.id %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                    {% else %}
                        <a href="{% url 'accounts:followsInDetail' username=likeuser.username category=post.category.name number=post.id %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                    {% endif %}
                {% endif %}
            </div>
        {% endfor %}
    </div>
</div>

main/templates/nowPost/nowPost.html
<article class="m-2 p-1 rounded-2 d-flex" style="border: 2px solid black; flex-direction: column;">
    <div class="m-2 rounded-2 d-flex" style="flex-direction: column;">
        <div class="d-flex justify-content-between">
            <!-- 글 제목 -->
            <h4 class="fw-bold mt-1">{{ post.title }}</h4>

            {% if user.id == owner.id %}
            <!-- 수정 및 삭제 -->
            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false"></button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'main:update' username=owner.username category=post.category.name number=post.id %}">수정하기</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:delete' username=owner.username category=post.category.name number=post.id %}">삭제하기</a></li>
                </ul>
            </div>
            {% endif %}
        </div>

        <div class="d-flex align-items-center" style="width: 100%;">
            <!-- 글 작성자 프로필 이미지 -->
            <div class="m-1" style="width: 30px; height: 30px; border-radius: 70%; overflow: hidden;">
                <img src="{{ owner.profile_image.url }}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
            </div>

            <!-- 글 작성자 아이디 및 작성 시간 -->
            <div class="mx-2">
                <p class="m-0" style="font-size: 1rem;">{{ owner.username }}</p>
                <p class="m-0" style="font-size: 0.75rem; color: rgb(143, 143, 143);">{{ post.updated_at|date:"Y년 n월 j일 A g:i" }}</p>
            </div>

            <!-- 이웃 추가 및 삭제 버튼 -->
            {% if user != post.user and user.is_authenticated %}
                {% if user in post.user.followers.all %}
                    <a href="{% url 'accounts:followsInDetail' username=post.user.username category=post.category.name number=post.id %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃해제</a>
                {% else %}
                    <a href="{% url 'accounts:followsInDetail' username=post.user.username category=post.category.name number=post.id %}" class="btn btn-secondary ms-auto" style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">이웃추가</a>
                {% endif %}
            {% endif %}
        </div>
        <hr>

        <!-- Post 이미지 -->
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="">
        {% endif %}

        <!-- 글 내용 -->
        <p> {{ post.content }} </p>
        <hr class="mt-0">
    </div>

    <div class="m-2">
        <!-- 포스트 공감 -->
        {% include 'nowPost/likes.html' %}
        <div class="collapse show comment-list" id="comment-list">
            <hr>
            <!-- 댓글, 답글 -->
            {% include 'nowPost/comment&reply.html' %}

        </div>

        <script type="text/javascript" src="/static/js/likes.js"></script>
        <script type="text/javascript" src="/static/js/comment.js"></script>
        <script type="text/javascript" src="/static/js/reply.js"></script>
    </div>
</article>

main/templates/nowPost/postNone.html
<article class="m-2 p-1 rounded-2 d-flex" style="border: 2px solid black; flex-direction: column;">
    <div class="m-2 rounded-2 d-flex" style="flex-direction: column;">
        게시된 글이 없습니다.
    </div>    
</article>