Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('home/', include('home.urls'), name='home'),
    path('', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/follows/', views.follows, name='follows'),
    path('<str:username>/follows/<str:category>/<int:number>', views.followsInDetail, name='followsInDetail'),
    
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('<str:username>/', views.main, name='main'),
    path('<str:username>/<str:category>/<int:number>/', views.detail, name='detail'),
    path('<str:username>/create/', views.create, name='create'),
    path('<str:username>/edit_introduce/', views.edit_introduce, name='edit_introduce'),
    path('<str:username>/<str:category>/<int:number>/delete/', views.delete, name='delete'),
    path('<str:username>/<str:category>/<int:number>/update/', views.update, name='update'),

    path('<str:username>/<str:category>/<int:number>/likes-async/', views.likes_async, name='likes-async'),

    path('<str:username>/<str:category>/<int:number>/comments/create/', views.comment_create, name='comment_create'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/update/', views.comment_update, name='comment_update'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/likes-async/', views.comment_likes_async, name='comment-likes-async'),  
  
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/create/', views.reply_create, name='reply_create'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/<int:reply_id>/delete/', views.reply_delete, name='reply_delete'),
    path('<str:username>/<str:category>/<int:number>/comments/<int:comment_id>/replys/<int:reply_id>/update/', views.reply_update, name='reply_update'),

    path('<str:username>/category', views.category, name='category'),
    path('<str:username>/category/create', views.Create_category, name='createCategory'),
    path('<str:username>/category/delete', views.Delete_category, name='deleteCategory'),

]

templates/_nav.html
<nav class="navbar navbar-expand-sm bg-body-tertiary">
    <div class="container-fluid">
      <!-- 최선단 버튼, 홈으로 이동 -->
      <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- 하위 버튼 목록 -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <!-- 로그인 하였을 경우 버튼 목록 -->
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'main:main' username=request.user.username %}">나의 블로그</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
          <!-- 로그인 하지 않았을 경우 버튼 목록 -->
          {% else %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'accounts:login' %}">로그인</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>